---
title: Inkfield Media
timezone: UTC
collections:
  clients:
    title: Clients
    output: true
    permalink: work
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
  work:
    title: Work
    output: true
    permalink: work
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: pages
  values:
    menu: menu
    excerpt_text: 
    excerpt_image: 
- scope:
    path: ''
    type: work
  values:
    permalink: "/work/:title/"
    link: 
    layout: fullscreen
    thumbnail_image: 
    video_number: 
    homepage_feature: 
- scope:
    path: ''
    type: clients
  values:
    permalink: "/clients/:title/"
    link: 
    layout: post
    logo_image: 
email: info@inkfieldmedia.com
mobile: "+44 7587 977 848"
address-line-1: 25 Hill Street
address-line-2: Mayfair W1J 5LW
address-line-3: London
copyright: Inkfield Media Â© 2017
google-analytics: 
google-lat: 51.508565
google-lng: -0.148539
showreel-video-id: 196885914
baseurl: 
description: 
permalink: pretty
markdown: redcarpet
highlighter: pygments
exclude:
- gulpfile.js
- package.json
- README*
- node_modules
- ".gitignore"
